name: CI
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
jobs:
  build-test:
    name: Build and test on Erlang/OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: [23, 24, '25.1.1']
        os: [ubuntu-latest, windows-latest]
    env:
      LATEST_OTP_RELEASE: '25.1.1'
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        id: install-erlang
        with:
          otp-version: ${{matrix.otp_version}}
          rebar3-version: '3.19'
      - name: Restore Dialyzer PLT files from cache
        uses: actions/cache@v3
        if: ${{ matrix.otp_version == env.LATEST_OTP_RELEASE && matrix.os == 'ubuntu-latest' }}
        with:
          path: _build/*/rebar3_*_plt
          key: dialyzer-plt-cache-${{ steps.install-erlang.outputs.otp-version }}-${{ runner.os }}-${{ hashFiles('rebar.config*') }}-v0
      - name: Compile
        run: rebar3 compile
      - name: Test
        run: rebar3 eunit --verbose
      - name: Dialyzer
        if: ${{ matrix.otp_version == env.LATEST_OTP_RELEASE && matrix.os == 'ubuntu-latest' }}
        run: rebar3 dialyzer
